### ISSUE TITLE
log "nothing to do"

### ISSUE THREAD

**Issue by rasooul** [klimaleksus/stable-diffusion-webui-anti-burn#1]
it just doesn't work ! I updated everything and nothing@
In the log it says" AntiBurn: nothing to do"

**Comment by aleksusklim** [comment]
Hm-m, I tried update to https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/ea9bd9fc7409109adcd61b897abc2c8881161256 and for me its working.

«nothing to do» means that AntiBurn don't have any stored latents when it needs to perform averaging.
Either because they all were skipped (Skip is larger than your Steps, or steps of second pass when highres.fix), or because it could not install a hook to grab them in the first place.

Can you confirm on default settings (20 steps of Euler a, AntiBurn enabled with Count=3, any simple prompt like "a cat")?
If it still won't work, probably another extension could be interfering. Try to disable any single one except for mine, and retry. (And then if it will work, try to figure out, which one that was – then I'll try to replicate).

If it would still fail, then your custom Settings of WebUI are somehow preventing AntiBurn to grab latents. (In that case, try to figure out what setting it could be; also worth trying to temporary rename `config.json` and restart WebUI to check).

**Comment by rasooul** [comment]
It works now, thank you so much for the reply.
I uninstalled and deleted the folder
Then reinstalled it from direct URL (before I was doing it from the list provided by WebUI!)
And now it works!

**Comment by klimaleksus** [comment]
OMG, you was actually right!
The code didn't work for pure img2img tab. So, for any img2img generations it printed "Nothing to do"…

Should be fixed now. The extension is needed to be updated in WebUI to pull new changes.

**Comment by aleksusklim** [comment]
OMG, you was actually right!
The code didn't work for pure img2img tab. So, for any img2img generations it printed "Nothing to do"…

Should be fixed now. The extension is needed to be updated in WebUI to pull new changes.

**Comment by rasooul** [comment]
Thank you
