### ISSUE TITLE
stop Hires fix pass not working as intended

### ISSUE THREAD

**Issue by t-Ghost-t** [klimaleksus/stable-diffusion-webui-anti-burn#4]
When set to 22 it stops my render at 22 regular steps rather than stopping at the 22nd hires fix step. I tried to set it to 123 (as I do 100 regular steps and 25 hires steps) as a workaround but the UI caps it to 80.
It begins counting from the very first step, instead of the hires steps.

**Comment by aleksusklim** [comment]
> When set to 22 it stops my render at 22 regular steps

This is what it does.

> but the UI caps it to 80.

You can edit your `ui-config.json` and change cap, as you would do for any other GUI control.

> It begins counting from the very first step, instead of the hires steps.

Intended behavior, because to stop the second pass you should use `Skip` but not `Stop`, and provide how many you want to skip from the end (rather than how many you want to keep at the beginning).
